version: '2'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:1000"
    volumes:
      - .:/html/laravel
      - ./laravel.conf:/etc/nginx/conf.d/laravel.conf
    networks:
      - net
  php:
    build:
      context: ./
      dockerfile: php.Dockerfile
    volumes:
      - .:/html/laravel
    networks:
      - net
  mysql:
    image: mysql:5.7.24
    container_name: todo-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - net

  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: todo-phpmyadmin
    ports:
      - "8080:80"
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      PMA_HOST: todo-mysql
    depends_on:
      - mysql
    networks:
      - net

networks:
  net:
    driver: bridge